[project]
name = "card-game"
description = "Stacks Card Game"
authors = ["SP19AHC15QDZJPDHTF5WQWKKZC6RE38W9D6VC56EH"]
telemetry = false
cache_dir = "./.clarinet"

[contracts.card-game-v2]
path = "contracts/card-game.clar"
clarity_version = 2
epoch = "3.0"

[contracts.stx-bouncer]
path = "contracts/stx-bouncer.clar"
clarity_version = 2
epoch = "3.0"
