#!/usr/bin/env node
// Creates a dated dev log entry as a draft PR — open issues become today's task list.
// Run once per day. Fill in the log as you work, then merge when done.

import { execSync } from "child_process";
import { writeFileSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");

function run(cmd, cwd = ROOT) {
  return execSync(cmd, { cwd, encoding: "utf8", stdio: "pipe" }).trim();
}

function today() {
  return new Date().toISOString().slice(0, 10);
}

async function main() {
  const date = today();
  const branch = `daily/${date}`;

  console.log(`Creating daily dev log for ${date}...\n`);

  // Abort if today's log already exists on remote
  const remoteBranches = run("git branch -r");
  if (remoteBranches.includes(branch)) {
    console.log(`Log for ${date} already exists. Branch: ${branch}`);
    console.log("Nothing to do — fill in the log and merge the open PR when done.");
    return;
  }

  // Pull open issues to pre-populate the task list
  let issues = [];
  try {
    issues = JSON.parse(
      run("gh issue list --state open --json number,title,labels --limit 15")
    );
  } catch {
    console.warn("Could not fetch issues — task list will be empty.");
  }

  run("git checkout main");
  run("git pull origin main --quiet");
  run(`git checkout -b ${branch}`);

  mkdirSync(resolve(ROOT, "dev-log"), { recursive: true });

  const taskLines = issues.length
    ? issues.map(i => {
        const label = i.labels[0]?.name ? ` [${i.labels[0].name}]` : "";
        return `- [ ] #${i.number}${label} — ${i.title}`;
      })
    : ["- [ ] _No open issues — add your tasks manually_"];

  const log = [
    `# Dev Log — ${date}`,
    "",
    "## Focus for today",
    "> _One sentence on what you're trying to accomplish._",
    "",
    "## Tasks",
    ...taskLines,
    "",
    "## Notes",
    "> _Technical decisions, blockers, useful links..._",
    "",
    "## End-of-day summary",
    "> _What got done? What carries over?_",
    "",
  ].join("\n");

  writeFileSync(resolve(ROOT, `dev-log/${date}.md`), log);

  run(`git add dev-log/${date}.md`);
  run(`git commit -m ${JSON.stringify(`chore: dev log ${date}`)}`);
  run(`git push origin ${branch}`);

  const prBody = [
    `## Dev Log — ${date}`,
    "",
    issues.length ? `**${issues.length} open issue(s) tracked as tasks:**` : "",
    ...issues.map(i => `- #${i.number} — ${i.title}`),
    "",
    "_Fill in the log throughout the day. Merge this PR when done._",
    "",
    "🤖 Generated by `scripts/daily-log.js`",
  ].filter(Boolean).join("\n");

  const prUrl = run(
    `gh pr create --title ${JSON.stringify(`chore: dev log ${date}`)} --body ${JSON.stringify(prBody)} --base main --head ${branch} --draft`
  );

  console.log(`Draft PR: ${prUrl}`);
  console.log(`Log file: dev-log/${date}.md`);
  console.log("\nFill in the log as you work. When the day wraps up, mark tasks done and merge the PR.");

  run("git checkout main");
}

main().catch(err => {
  console.error("[daily-log]", err.message);
  process.exit(1);
});
