#!/usr/bin/env node
// Checks for outdated npm packages in the project root, then creates a branch + PR updating them.

import { execSync } from "child_process";
import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");

function run(cmd, cwd = ROOT) {
  return execSync(cmd, { cwd, encoding: "utf8", stdio: "pipe" }).trim();
}

function today() {
  return new Date().toISOString().slice(0, 10);
}

function getRepoSlug() {
  const url = run("git remote get-url origin");
  const m = url.match(/github\.com[/:](.+?\/.+?)(?:\.git)?$/);
  return m ? m[1] : null;
}

async function main() {
  console.log("Checking for outdated packages...\n");

  let outdated = {};
  try {
    // npm outdated exits 1 when packages are outdated — capture stdout manually
    execSync("npm outdated --json", { cwd: ROOT, stdio: "pipe" });
  } catch (err) {
    try { outdated = JSON.parse(err.stdout || "{}"); } catch { outdated = {}; }
  }

  const updates = Object.entries(outdated)
    .filter(([, info]) => info.wanted && info.wanted !== info.current)
    .map(([name, info]) => ({ name, current: info.current, wanted: info.wanted }));

  if (updates.length === 0) {
    console.log("All packages are up to date. Nothing to do.");
    return;
  }

  console.log(`Found ${updates.length} outdated package(s):`);
  updates.forEach(u => console.log(`  ${u.name}: ${u.current} → ${u.wanted}`));

  const branch = `chore/dep-updates-${today()}`;

  // Abort if branch already exists on remote
  const remoteBranches = run("git branch -r");
  if (remoteBranches.includes(branch)) {
    console.log(`\nBranch ${branch} already exists on remote. Run again tomorrow or close the existing PR first.`);
    return;
  }

  run("git checkout main");
  run("git pull origin main --quiet");
  run(`git checkout -b ${branch}`);

  // Update package.json in place
  const pkgPath = resolve(ROOT, "package.json");
  const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));

  for (const { name, wanted } of updates) {
    if (pkg.dependencies?.[name])    pkg.dependencies[name]    = `^${wanted}`;
    if (pkg.devDependencies?.[name]) pkg.devDependencies[name] = `^${wanted}`;
  }

  writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n");

  console.log("\nRunning npm install...");
  try {
    execSync("npm install", { cwd: ROOT, stdio: "inherit" });
  } catch {
    console.warn("npm install finished with warnings — continuing.");
  }

  run("git add package.json package-lock.json");

  const commitBody = updates.map(u => `- ${u.name}: ${u.current} → ${u.wanted}`).join("\n");
  run(`git commit -m ${JSON.stringify(`chore: update ${updates.length} npm package(s)\n\n${commitBody}`)}`);
  run(`git push origin ${branch}`);

  const prBody = [
    "## Summary",
    `Bumps ${updates.length} package(s) to their latest wanted versions as reported by \`npm outdated\`.`,
    "",
    "## Updated packages",
    ...updates.map(u => `- \`${u.name}\`: \`${u.current}\` → \`${u.wanted}\``),
    "",
    "## Test plan",
    "- [ ] `npm run dev` starts without errors",
    "- [ ] No breaking changes introduced by updated packages",
    "",
    "🤖 Generated by `scripts/dep-auditor.js`",
  ].join("\n");

  const prUrl = run(
    `gh pr create --title ${JSON.stringify(`chore: dependency updates ${today()}`)} --body ${JSON.stringify(prBody)} --base main --head ${branch}`
  );

  console.log(`\nPR opened: ${prUrl}`);
  run("git checkout main");
}

main().catch(err => {
  console.error("[dep-auditor]", err.message);
  process.exit(1);
});
